package backward;
import com.ftn.sbnz.model.models.Examination;
import com.ftn.sbnz.model.models.Symptom;
import com.ftn.sbnz.model.models.enums.SymptomName;
import com.ftn.sbnz.model.models.Diagnosis;
import com.ftn.sbnz.model.models.Location;
import com.ftn.sbnz.model.models.enums.Disease;
import java.util.List;

query isContainedIn( SymptomName x, SymptomName y, Examination e)
  Location( x, y; )
  or
  ( Location( z, y; ) and isContainedIn( x, z, e; ) )
  $s1 : Symptom(name == x) from e.symptoms
end

query Bronhiolitis( Examination $e )
    isContainedIn( SymptomName.WHEEZING, SymptomName.DYSPNEA, $e; )
end

query Asthma( Examination $e )
    isContainedIn( SymptomName.PROLONGED_EXPIRATION, SymptomName.DYSPNEA, $e; )
end

query Pneumonia( Examination $e )
    isContainedIn( SymptomName.CHEST_PAIN, SymptomName.DYSPNEA, $e; )
end

query Anemia( Examination $e )
    isContainedIn( SymptomName.TACHYCARDIA, SymptomName.DYSPNEA, $e; )
end


