package test;
import com.ftn.sbnz.model.models.Baby;
import com.ftn.sbnz.model.models.Examination;
import com.ftn.sbnz.model.models.Diagnosis;
import com.ftn.sbnz.model.dtos.ExaminationDTO;
import com.ftn.sbnz.model.models.enums.VaccinationType;
import com.ftn.sbnz.model.models.Symptom
import com.ftn.sbnz.model.models.enums.SymptomName
import com.ftn.sbnz.model.models.Vaccination
import java.time.LocalDate
import java.util.ArrayList;


//rule "Check Baby Weight and Height"
//when
//    $b : Baby()
//    $e : Examination(
//        (getWeight() - $b.getWeight()) < 0.6 ||
//        (getHeight() - $b.getHeight()) < 1.5
//    ) from $b.getLastExamination()
//then
//    Symptom s = new Symptom(null, SymptomName.FAILURE_TO_THRIVE, 4L, 1);
//    java.util.List<Symptom> updated = new java.util.ArrayList<>($e.getSymptoms());
//    updated.add(s);
//
//    modify($e) {  setSymptoms(updated) }
//
//    System.out.println("Baby " + $b.getFirstName() + " " + $b.getLastName() + " has failure to thrive.");
//end
//
//rule "Check if Baby has Mild Temperature"
//when
//    $e : Examination(
//       getTemperature() > 37.0 &&
//       getTemperature() <= 37.5)
//then
//    Symptom s = new Symptom(null, SymptomName.MILD_FEVER, 5L, 1);
//    java.util.List<Symptom> updated = new java.util.ArrayList<>($e.getSymptoms());
//    updated.add(s);
//
//    modify($e) {  setSymptoms(updated) }
//
//    System.out.println("Baby " + $e.getBaby().getFirstName() + " " + $e.getBaby().getLastName() + " has mild fever.");
//end
//
//rule "Check if Baby has Moderate Temperature"
//when
//    $e : Examination(
//       getTemperature() > 37.5 &&
//       getTemperature() <= 38.5)
//then
//    Symptom s = new Symptom(null, SymptomName.MODERATE_FEVER, 5L, 1);
//    java.util.List<Symptom> updated = new java.util.ArrayList<>($e.getSymptoms());
//    updated.add(s);
//
//    modify($e) {  setSymptoms(updated) }
//
//    System.out.println("Baby " + $e.getBaby().getFirstName() + " " + $e.getBaby().getLastName() + " has moderate fever.");
//end
//
//rule "Check if Baby has High Temperature"
//when
//    $e : Examination(
//       getTemperature() > 38.5)
//then
//    Symptom s = new Symptom(null, SymptomName.HIGH_FEVER, 5L, 1);
//    java.util.List<Symptom> updated = new java.util.ArrayList<>($e.getSymptoms());
//    updated.add(s);
//
//    modify($e) {  setSymptoms(updated) }
//
//    System.out.println("Baby " + $e.getBaby().getFirstName() + " " + $e.getBaby().getLastName() + " has high fever.");
//end
//
//rule "Check Baby Heart Rate"
//when
//    $e : Examination(
//        getHeartRate() > 180)
//then
//    Symptom s = new Symptom(null, SymptomName.TACHYCARDIA, 4L, 1);
//    java.util.List<Symptom> updated = new java.util.ArrayList<>($e.getSymptoms());
//    updated.add(s);
//
//    modify($e) {  setSymptoms(updated) }
//
//    System.out.println("Baby " + $e.getBaby().getFirstName() + " " + $e.getBaby().getLastName() + " has tahicardia.");
//end
//
//rule "Check Baby Respiration Rate"
//when
//    $e : Examination(
//        getRespirationRate() > 48)
//then
//    Symptom s = new Symptom(null, SymptomName.TACHYPNEA, 4L, 1);
//    java.util.List<Symptom> updated = new java.util.ArrayList<>($e.getSymptoms());
//    updated.add(s);
//
//    modify($e) {  setSymptoms(updated) }
//
//    System.out.println("Baby " + $e.getBaby().getFirstName() + " " + $e.getBaby().getLastName() + " has tachypnea.");
//end

rule "Second Dose Euvax B and BCG After 1 Month"
no-loop
when
    $b: Baby()
    $e: Examination(symptoms.isEmpty()) from $b.getLastExamination()
then
    Vaccination vaccination = new Vaccination(null, VaccinationType.EUVAX_B, LocalDate.now(), 2);
    java.util.List<Vaccination> updated = new java.util.ArrayList<>($b.getVaccinations());
    updated.add(vaccination);
//    insert(vaccination)
    modify($b){ setVaccinations(updated) }

    System.out.println("Baby " + $b.firstName + " " + $b.lastName + " is ready for second dose of Euvax B vaccination.");
end
