package com.ftn.sbnz.model.models.enums;

public enum Disease {
    ESOPHAGEAL_STENOSIS,
    ESOPHAGEAL_ATRESIA,
    PROJECTILE_VOMITING,
    FAILURE_TO_GAIN_WEIGHT,
    PALLOR, 
    BRONCHIOLITIS,
    PNEUMONIA,
    ASTHMA,
    ANEMIA,
    CONJUNCTIVITIS,
    PENFIGUS,
    PHYSIOLOGICAL_JAUNDICE,
    HEART_DEFECT,
    URINARY_TRACT_INFECTION
}
