package com.ftn.sbnz.model.models.enums;

public enum SymptomName {
    MILD_FEVER,
    MODERATE_FEVER,
    HIGH_FEVER,
    PALE_SKIN,
    COUGH,
    FAILURE_TO_THRIVE,
    VOMITING,
    TACHYCARDIA,
    TACHYPNEA,
    DYSPNEA,
    FATIGUE,
    WHEEZING,
    CHEST_PAIN,
    PROLONGED_EXPIRATION,
    APPETITE_LOSS,
    LOW_ERITROCYTES,
    YELLOW_SKIN,
    BLUE_MOUTH,
    SWEATING,
    BLOOD_IN_URINE,
    UNPLEASANT_URINE_ODOR,
    REDDNES_OF_SKIN,
    PIMPLED_SKIN,
    VOMITING_IN_STREAM
}
